Repository munich-quantum-toolkit/naviz, pull requests merged in 2025-08, with the labels that each got.

#102 👷 Extend workflows
  .github/release-drafter.yml
  .github/workflows/code-ql-python.yml
  .github/workflows/lint-python.yml
  .github/workflows/lint-rust.yaml
  .github/workflows/publish-crates.yaml
  .github/workflows/release-drafter.yml
  pyproject.toml
Labels: continuous integration

#131 🎨🐍 Streamline Python bindings
  Cargo.lock
  Cargo.toml
  bindings/Cargo.toml
  bindings/LICENSE
  bindings/src/lib.rs
  docs/conf.py
  pyproject.toml
  python/README.md
Labels: refactor, rust, python

#132 :sparkles: Improved error messages
  gui/src/app.rs
  gui/src/error.rs
  gui/src/errors.rs
  gui/src/menu.rs
  parser/src/common.rs
  parser/src/common/position.rs
  parser/src/config/lexer.rs
  parser/src/config/parser.rs
  parser/src/input/lexer.rs
  parser/src/input/parser.rs
  parser/src/lib.rs
  parser/src/test_utils.rs
Labels: enhancement, Area: File Parser, Area: GUI, refactor, rust, usability

#156 🚚 Prepare move to MQT organization
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/release.yaml
  .github/support.md
  .github/workflows/github-pages.yaml
  .readthedocs.yml
  Cargo.toml
  README.md
  doc/FileFormat.md
  docs/conf.py
  docs/contributing.md
  docs/file_format.md
  docs/index.md
  docs/installation.md
  docs/support.md
  docs/usage.md
  pyproject.toml
Labels: documentation

#161 ✏️ Fix typo in README
  .pre-commit-config.yaml
  README.md
  pyproject.toml
Labels: documentation, fix
