Repository munich-quantum-toolkit/naviz, pull requests merged in 2025-09, with the labels that each got.

#157 :bug: Dynamic content padding calculation for `Layout`
  renderer/src/renderer.rs
Labels: bug, Area: Renderer, rust, usability, fix

#165 👷📝 Set up templating
  .github/workflow_inputs/release_drafter_categories.json
  .github/workflows/templating.yml
Labels: documentation, continuous integration

#191 🔥 Drop support for Python 3.9
  docs/conf.py
  pyproject.toml
  uv.lock
Labels: dependencies, python, minor

#211 🍎 Restore support for x86 macOS systems
  .github/workflows/desktop-build.yaml
  .github/workflows/python.yaml
  .github/workflows/test.yaml
Labels: dependencies, continuous integration
